//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// This code was auto-generated by ContractConverterTools.AsyncContractConverterTool, version 1.9.0.0
// 
/*
**
**COPYRIGHT:
**    This software program is furnished to the user under license
**  by METTLER TOLEDO AutoChem, and use thereof is subject to applicable 
**  U.S. and international law. This software program may not be 
**  reproduced, transmitted, or disclosed to third parties, in 
**  whole or in part, in any form or by any manner, electronic or
**  mechanical, without the express written consent of METTLER TOLEDO 
**  AutoChem, except to the extent provided for by applicable license.
**
**    Copyright © 2011 by Mettler Toledo AutoChem.  All rights reserved.
**
**ENDHEADER:
**/

using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Text;
using System.Threading.Tasks;

namespace AutoChem.Core.CentralDataServer.Instruments
{
    /// <summary>
    /// This is a simple client that connects to the InstrumentManagementService.
    /// </summary>
    public class InstrumentManagementAdminClientAsync : ClientBase<IInstrumentManagementServiceAdminAsync>, IInstrumentManagementServiceAdminAsync
    {
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="binding">binding (passed to base class)</param>
        /// <param name="remoteAddress">endpoint address (passed to base class)</param>
        public InstrumentManagementAdminClientAsync(Binding binding, EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        /// <summary>
        /// Adds an instrument to the system.
        /// </summary>
        public IAsyncResult BeginAddInstrument(string hostAddress, string hostDescription, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginAddInstrument(hostAddress, hostDescription, callback, asyncState);
        }

        ///<summary>
        /// Returns the result of calling AddInstrument on the server that corresponds to the result.
        ///</summary>
        public InstrumentInfo EndAddInstrument(System.IAsyncResult result)
        {
            return base.Channel.EndAddInstrument(result);
        }

        ///<summary>
        /// Returns the result of calling AddInstrument on the server as an async Task.
        ///</summary>
        public Task<InstrumentInfo> AddInstrumentAsync(string hostAddress, string hostDescription)
        {
            var taskSource = new TaskCompletionSource<InstrumentInfo>();
            BeginAddInstrument(hostAddress, hostDescription, asyncResult =>
            {
                try
                {
                    var result = EndAddInstrument(asyncResult);
                    taskSource.SetResult(result);
                }
                catch (Exception exception)
                {
                    taskSource.SetException(exception);
                }
            }, null);
            return taskSource.Task;
        }

        ///<summary>
        /// Calls AddInstrument on the server and waits for a response (synchronous).
        /// This should not be called on a UI thread
        ///</summary>
        public InstrumentInfo AddInstrument(string hostAddress, string hostDescription)
        {
            IAsyncResult result = BeginAddInstrument(hostAddress, hostDescription, null, null);
            result.AsyncWaitHandle.WaitOne();

            return EndAddInstrument(result);
        }

        /// <summary>
        /// Adds an instrument to the system.
        /// </summary>
        public IAsyncResult BeginRemoveInstrument(string hostAddress, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginRemoveInstrument(hostAddress, callback, asyncState);
        }

        ///<summary>
        /// Returns the result of calling RemoveInstrument on the server that corresponds to the result.
        ///</summary>
        public void EndRemoveInstrument(System.IAsyncResult result)
        {
            base.Channel.EndRemoveInstrument(result);
        }

        ///<summary>
        /// Returns the result of calling RemoveInstrument on the server as an async Task.
        ///</summary>
        public Task RemoveInstrumentAsync(string hostAddress)
        {
            var taskSource = new TaskCompletionSource<object>();
            BeginRemoveInstrument(hostAddress, asyncResult =>
            {
                try
                {
                    EndRemoveInstrument(asyncResult); var result = new object();
                    taskSource.SetResult(result);
                }
                catch (Exception exception)
                {
                    taskSource.SetException(exception);
                }
            }, null);
            return taskSource.Task;
        }

        ///<summary>
        /// Calls RemoveInstrument on the server and waits for a response (synchronous).
        /// This should not be called on a UI thread
        ///</summary>
        public void RemoveInstrument(string hostAddress)
        {
            IAsyncResult result = BeginRemoveInstrument(hostAddress, null, null);
            result.AsyncWaitHandle.WaitOne();

            EndRemoveInstrument(result);
        }
    }
}
