//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// This code was auto-generated by ContractConverterTools.AsyncContractConverterTool, version 1.9.0.0
// 
/*
**
**COPYRIGHT:
**    This software program is furnished to the user under license
**  by METTLER TOLEDO AutoChem, and use thereof is subject to applicable 
**  U.S. and international law. This software program may not be 
**  reproduced, transmitted, or disclosed to third parties, in 
**  whole or in part, in any form or by any manner, electronic or
**  mechanical, without the express written consent of METTLER TOLEDO 
**  AutoChem, except to the extent provided for by applicable license.
**
**    Copyright © 2011 by Mettler Toledo AutoChem.  All rights reserved.
**
**ENDHEADER:
**/

using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;

namespace AutoChem.Core.CentralDataServer.Config
{

    /// <summary>
    /// Defines the interface for the configuration management service.
    /// </summary>
    [ServiceContract(Name = "IConfigurationManagementService", Namespace = ServicesHelper.ServiceNameSpace)]
    public interface IConfigurationManagementServiceAsync
    {
        /// <summary>
        /// Gets the configuration settings for the central data server relevant to an experiment provider such as iControl or ic IR.
        /// </summary>
        [OperationContract(AsyncPattern=true)]
        IAsyncResult BeginGetExperimentProviderSettings(System.AsyncCallback callback, object asyncState);

        ///<summary>
        /// Returns the result of calling GetExperimentProviderSettings on the server that corresponds to the result.
        ///</summary>
        ExperimentProviderSettings EndGetExperimentProviderSettings(System.IAsyncResult result);

#if !SILVERLIGHT
        ///<summary>
        /// Returns the result of calling GetExperimentProviderSettings on the server as an async Task.
        ///</summary>
        [OperationContract(AsyncPattern=true)]
        Task<ExperimentProviderSettings> GetExperimentProviderSettingsAsync();
#endif

        ///<summary>
        /// Calls GetExperimentProviderSettings on the server and may or may not wait for a response see client.
        /// If this is synchronous it should not be called on the UI thread.
        ///</summary>
        ExperimentProviderSettings GetExperimentProviderSettings();

        /// <summary>
        /// Gets the configuration settings for the central data server.
        /// </summary>
        [OperationContract(AsyncPattern=true)]
        IAsyncResult BeginGetPartialConfigurationSettings(System.AsyncCallback callback, object asyncState);

        ///<summary>
        /// Returns the result of calling GetPartialConfigurationSettings on the server that corresponds to the result.
        ///</summary>
        ConfigurationSettings EndGetPartialConfigurationSettings(System.IAsyncResult result);

#if !SILVERLIGHT
        ///<summary>
        /// Returns the result of calling GetPartialConfigurationSettings on the server as an async Task.
        ///</summary>
        [OperationContract(AsyncPattern=true)]
        Task<ConfigurationSettings> GetPartialConfigurationSettingsAsync();
#endif

        ///<summary>
        /// Calls GetPartialConfigurationSettings on the server and may or may not wait for a response see client.
        /// If this is synchronous it should not be called on the UI thread.
        ///</summary>
        ConfigurationSettings GetPartialConfigurationSettings();
    }
}
